[project]
name = "utsikt-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-auth>=2.56.3",
    "google-cloud-bigquery>=3.43.0",
    "pandas>=3.0.5",
    "plotly>=6.9.0",
    "python-dotenv>=1.1.1",
    "streamlit>=1.61.1",
]

[tool.sqlfluff.core]
dialect = "bigquery"
max_line_length = 0

[dependency-groups]
dev = [
    "sqlfluff>=4.3.0",
]
