SELECT
    ventestatus_kode,
    ventestatus_beskrivelse,
    fagomrade_kode,
    fagomrade_navn,
    faggruppe_navn,
    status_registrert_dato,
    status_avsluttet_dato,
    varighet_dager,
    gjeldende_flagg,
    antall_beregninger
FROM
    `utsikt-dev-3609.venteregister.agg_beregninger_manuell_ventestatus_per_ventestatus_varighet_fagomrade_dag`
