name: Build and deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Determine what to do
        id: changed-files
        uses: "nais/what-changed@main"
        with:
          files: .nais/app.yaml
      - name: Build and push image and SBOM to OCI registry
        if: steps.changed-files.outputs.changed != 'only-inputs'
        uses: nais/docker-build-push@8e41f1f58749b9248e376c25d33bfbdd2b1163c0 # v0
        id: docker-build-push
        with:
          team: utsikt
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b # v2
        env:
          CLUSTER: "dev-gcp"
          RESOURCE: .nais/dev_app.yaml
          VAR: image=${{ steps.docker-build-push.outputs.image }}
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b # v2
        env:
          CLUSTER: "prod-gcp"
          RESOURCE: .nais/prod_app.yaml
          VAR: image=${{ steps.docker-build-push.outputs.image }}
