name: Build and deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: Determine what to do
        id: changed-files
        uses: "nais/what-changed@main"
        with:
          files: .nais/app.yaml
      - name: Build and push image and SBOM to OCI registry
        if: steps.changed-files.outputs.changed != 'only-inputs'
        uses: nais/docker-build-push@05dbb6091b30bd84279c6d64a45ef8782fd410a5 # v0
        id: docker-build-push
        with:
          team: utsikt
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@8a6fb62e73f837af6287d5db84a46ea96aa6c30d # v2
        env:
          CLUSTER: "dev-gcp"
          RESOURCE: .nais/dev_app.yaml
          VAR: image=${{ steps.docker-build-push.outputs.image }}
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@8a6fb62e73f837af6287d5db84a46ea96aa6c30d # v2
        env:
          CLUSTER: "prod-gcp"
          RESOURCE: .nais/prod_app.yaml
          VAR: image=${{ steps.docker-build-push.outputs.image }}
